<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Categories Report</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: Arial, sans-serif;
            color: #333;
            background: #fff;
        }
        
        .header {
            background: linear-gradient(135deg, #E8997A 0%, #7CB9C8 100%);
            color: white;
            padding: 30px;
            text-align: center;
            margin-bottom: 20px;
        }
        
        .header h1 {
            font-size: 28px;
            margin-bottom: 5px;
        }
        
        .header p {
            font-size: 12px;
            opacity: 0.9;
        }
        
        .meta {
            display: flex;
            justify-content: space-between;
            margin-bottom: 20px;
            font-size: 12px;
            color: #666;
            padding: 0 10px;
        }
        
        .meta div {
            margin-bottom: 5px;
        }
        
        table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 20px;
        }
        
        table thead {
            background-color: #f5f5f5;
            border-top: 2px solid #E8997A;
            border-bottom: 2px solid #E8997A;
        }
        
        table th {
            padding: 12px;
            text-align: left;
            font-weight: 600;
            font-size: 12px;
            color: #333;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }
        
        table td {
            padding: 10px 12px;
            font-size: 11px;
            border-bottom: 1px solid #eee;
        }
        
        table tbody tr:hover {
            background-color: rgba(232, 153, 122, 0.05);
        }
        
        .summary {
            background-color: #f9f9f9;
            padding: 15px;
            border-left: 4px solid #7CB9C8;
            margin: 20px 0;
            font-size: 12px;
        }
        
        .summary strong {
            color: #7CB9C8;
        }
        
        .footer {
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #eee;
            font-size: 10px;
            color: #999;
            text-align: center;
        }
        
        .badge {
            display: inline-block;
            background: linear-gradient(135deg, rgba(232, 153, 122, 0.1), rgba(124, 185, 200, 0.1));
            color: #3A3A36;
            padding: 4px 8px;
            border-radius: 12px;
            font-weight: 600;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>📋 Categories Report</h1>
        <p>Inventory Management System</p>
    </div>
    
    <div class="meta">
        <div><strong>Generated:</strong> {{ now()->format('M d, Y H:i:s') }}</div>
        <div><strong>Total Categories:</strong> {{ $categories->count() }}</div>
        <div><strong>Total Products:</strong> {{ $total_products }}</div>
    </div>
    
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Category Name</th>
                <th>Description</th>
                <th style="text-align: center;">Products</th>
                <th>Created</th>
            </tr>
        </thead>
        <tbody>
            @foreach($categories as $category)
            <tr>
                <td>#{{ $category->id }}</td>
                <td><strong>{{ $category->name }}</strong></td>
                <td>{{ $category->description ?? '—' }}</td>
                <td style="text-align: center;">
                    <span class="badge">{{ $category->products_count }} items</span>
                </td>
                <td>{{ $category->created_at->format('M d, Y') }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    
    <div class="summary">
        <strong>Summary:</strong>
        Total categories: <strong>{{ $categories->count() }}</strong> | 
        Average products per category: <strong>{{ round($total_products / max($categories->count(), 1), 1) }}</strong>
    </div>
    
    <div class="footer">
        <p>This is an automated report generated by the Inventory Management System.</p>
        <p>© {{ date('Y') }} Inventory System. All rights reserved.</p>
    </div>
</body>
</html>
